services:
  server:
    build:
      context: ./Server
    ports:
      - "8080:8080"
    environment:
      - GEMINI_API_KEY=AIzaSyDqwfgVhrCImU768Hse0fd87cJJmIaaaHw

  client:
    image: nginx
    ports:
      - "3000:80"
    volumes:
      - ./Client:/usr/share/nginx/html
    depends_on:
      - server